# Generated by Django 2.2.5 on 2019-10-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_auto_20191010_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
