# Generated by Django 2.2.5 on 2019-10-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_auto_20191010_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='max_salary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='min_salary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='position_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
