# Generated by Django 2.2.5 on 2019-11-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('top_skills', models.CharField(blank=True, max_length=200, null=True)),
                ('current_job', models.CharField(blank=True, max_length=200, null=True)),
                ('loc', models.CharField(blank=True, max_length=200, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
                ('certs', models.CharField(blank=True, max_length=200, null=True)),
                ('pubs', models.CharField(blank=True, max_length=200, null=True)),
                ('honors', models.CharField(blank=True, max_length=200, null=True)),
                ('summ', models.CharField(blank=True, max_length=200, null=True)),
                ('work_exp', models.CharField(blank=True, max_length=200, null=True)),
                ('edu', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
